### ISSUE TITLE
No results show up

### ISSUE THREAD

**Issue by bushblade** [AckslD/nvim-neoclip.lua#5]
Hi I have added this plugin as per the README and have in my Telescope settings
`telescope.load_extension("neoclip")`

But I don't see any results in :Telescope neoclip
![Screenshot_2021-08-18_13-17-01](https://user-images.githubusercontent.com/21976188/129901347-b1dcbe63-1dd2-4caa-a50d-bef42c43ccc3.png)

I do have yanked text in my registers
![Screenshot_2021-08-18_13-49-18](https://user-images.githubusercontent.com/21976188/129901382-e5f2f4ef-15e8-4862-82ba-f8f62c5a060a.png)

I also sometimes see these errors in my registers after installing the plugin.
![Screenshot_2021-08-18_13-52-12](https://user-images.githubusercontent.com/21976188/129901468-97eaac6c-bd60-4553-a22b-44b6c3b14882.png)

**Comment by bushblade** [comment]
Hi thanks for the reply
That outputs an empty table `{}`
And yes I can confirm...
![Screenshot_2021-08-18_16-54-52](https://user-images.githubusercontent.com/21976188/129930979-1577b778-0e00-48aa-8cc5-9ce4cee5c0fe.png)

**Comment by AckslD** [comment]
I see, I'll try to see why it doesn't work when you synchronise your system clipboard with vim with the `unnamedplus` option.

That being said, if you do synchronise with system clipboard, you could I guess just as well use something like `clipmenu`? Although I'm of course very happy that you want to use neoclip, but maybe that's an alternative at least until I fixed this :)

**Comment by bushblade** [comment]
Even if I comment out `unamedplus` option and restart nvim, I still see no results.

**Comment by AckslD** [comment]
Hmm, but you do call `require('neoclip').setup()` on startup?

**Comment by bushblade** [comment]
Yes I have in my load-plugins.lua
```lua
    use {
      "AckslD/nvim-neoclip.lua",
      config = function()
        require("neoclip").setup()
      end
    }
```

**Comment by AckslD** [comment]
What does
```
:autocmd TextYankPost
```
give you?

**Comment by bushblade** [comment]
![Screenshot_2021-08-18_21-23-02](https://user-images.githubusercontent.com/21976188/129967012-dcaffa68-ab79-4c3c-b5e2-64e14caa3ff4.png)

**Comment by AckslD** [comment]
Hmm, so it's not setup properly, should have one for neoclip:
```
:autocmd TextYankPost
--- Autocommands ---
TextYankPost
    *         silent! lua vim.highlight.on_yank{higroup = "IncSearch", timeout = 150, on_visual = true}
neoclip  TextYankPost
    *         :lua require("neoclip.handlers").handle_yank_post()
Press ENTER or type command to continue
```

Do you change these autocommands in your config?

**Comment by bushblade** [comment]
I have this in my config
```lua
-- highlight on yank
vim.cmd [[au TextYankPost * silent! lua vim.highlight.on_yank()]]
```
But just tried commenting that out and reloading, no change.

**Comment by bushblade** [comment]
(Here is my config)[https://github.com/bushblade/nvim.git] if that helps.

**Comment by AckslD** [comment]
This is very strange since the `setup` is just:
```lua
M.setup = function(opts)
    settings.setup(opts)
    setup_auto_command()
end
```
which calls
```lua
local function setup_auto_command()
    vim.cmd([[
        augroup neoclip
            autocmd!
            autocmd TextYankPost * :lua require("neoclip.handlers").handle_yank_post()
        augroup end
    ]])
end
```

**Comment by bushblade** [comment]
I just tried a minimal config with only telescope and neoclip, no options or other settings and still see the same empty results after doing a few yanks.
![Screenshot_2021-08-18_21-53-28](https://user-images.githubusercontent.com/21976188/129970737-87597cc1-e89e-49ae-8029-b0219ac92e10.png)

**Comment by AckslD** [comment]
Very strange! I'm mostly out of ideas for now... Could you maybe insert some print statements in the 'neoclip' code setting up the autocommand to see if it's actually executed?

**Comment by bushblade** [comment]
Ok so I edited neoclip.lua with the following
```lua
M.setup = function(opts)
  print("Just what is going on here...")
  settings.setup(opts)
  setup_auto_command()
end
```
Then reloaded nvim and yanked a few times, I see no print .

**Comment by bushblade** [comment]
Sorry realised that was the wrong function so then did
```lua
local function setup_auto_command()
  print("in setup_auto_command")
  vim.cmd(
    [[
        augroup neoclip
            autocmd!
            autocmd TextYankPost * :lua require("neoclip.handlers").handle_yank_post()
        augroup end
    ]]
  )
end
```
But nothing printed on a subsequent reload and yank.

**Comment by AckslD** [comment]
Also not under
```
:messages
```
?

In that case it seems very strange that you call `setup` in your config but don't see the print on the first line of that function

**Comment by bushblade** [comment]
It does actually flash up momentarily as nvim starts then disappears.

**Comment by bushblade** [comment]
Ok I got it working by calling setup in my telescope-settings.lua
![Screenshot_2021-08-18_22-44-23](https://user-images.githubusercontent.com/21976188/129976319-89407c97-af83-431b-93d4-b79d8c61a3bd.png)
So using as per the README..
```lua
    use {
      "AckslD/nvim-neoclip.lua",
      config = function()
        require("neoclip").setup()
      end
    }
```
With a config function doesn't actually work?

**Comment by bushblade** [comment]
However when I hit enter on a result it takes me to an empty buffer?

**Comment by AckslD** [comment]
For me it works with a config function, see my config here:
https://gitlab.com/AckslD/config/-/blob/master/nvim/lua/plugins.lua#L1726

If you figure something more out I'd be happy to hear it but not sure at this point why it doesn't work for you :/

**Comment by AckslD** [comment]
Btw did you compile packer after adding the config function?

**Comment by bushblade** [comment]
Hi, no I did not :PackerCompile, does that make a difference?

**Comment by bushblade** [comment]
Ok so I can confirm that all works as it should after I run :PackerCompile
I guess I've learned something, thanks for taking the time to respond and the extension, I'll close.

**Comment by bushblade** [comment]
Ah I may have spoken too soon, I'm still taken to a blank register after hitting enter on a result.
Going back to the last buffer I was in and hitting p doesn't put the selected result but instead the last thing I yanked.
Should I open a new issue?

**Comment by AckslD** [comment]
@bushblade Yeah, would be great if you open a new issue for that

**Comment by Sleepful** [comment]
with lazy vim I had to do this

```
    config = function(LazyV, opts)
      require("neoclip").setup(opts)
    end,
```

**Comment by DuncanvR** [comment]
> note that with lazy you can also do `config = true` if you don't want to pass any opts or instead configure the `opts` field

Would it be fitting to add something like that to the Troubleshooting section in the readme?

I'm using the following bit of Lazy config now.
```
{
   "nvim-telescope/telescope.nvim",
   dependencies = {
      { "AckslD/nvim-neoclip.lua", config = true },
      { "nvim-lua/plenary.nvim" },
   },
   config = function(_, opts)
      local telescope = require("telescope")
      telescope.setup(opts)
      telescope.load_extension("neoclip")
   end,
}
```

**Comment by AckslD** [comment]
@DuncanvR, just so understand, what exactly are you suggesting to add to the Troubleshooting section?

**Comment by DuncanvR** [comment]
I was struggling with getting neoclip to work for about an hour yesterday. It wasn't until I saw [your remark](https://github.com/AckslD/nvim-neoclip.lua/issues/5#issuecomment-1582740931) that I realised Lazy doesn't always call `setup()`, but only if `config = true` or `opts = {...}` is specified. Granted, that's mostly me not understanding how Lazy works, but judging from the number of similar *"it's not working"* issues in this repo, it seems to be a recurring problem for people. So I figured it might be worthwhile to add a line about it to the Troubleshooting section.

However, now that I've thought about it some more, I'd actually suggest changing that Troubleshooting section altogether. With my suggestion above, it'd be three bullet points with somewhat random things one might try if it's not working. I think it would help if instead it'd list the diagnostic steps I've seen you take in the comments on these issues. Something like a decision tree, e.g.
> 1. What is the output of `:lua print(vim.inspect(require('neoclip.storage').get()))` after yanking some lines?
>    1. If it's 
>       ```
>       {
>          macros = {...},
>          yanks = {...},
>       }
>       ```
>       with some data where the `...`s are, neoclip is working.
>    1. If it's 
>       ```
>       {
>          macros = {},
>          yanks = {},
>       }
>       ```
>       i.e. without data, despite yanking or recording, goto step B;
>    1. If it's `{}` or you get an error, neoclip was not correctly loaded, goto step A;
> 1. What is the output of `:autocmd TextYankPost`?
>    1. If it's
>       ```
>       neoclip  TextYankPost
>       *:lua require("neoclip.handlers").handle_yank_post()
>       ```
>       the `setup()` function has been executed.
>    1. Otherwise ...

I'd hope this would make it easier for folks to diagnose problems themselves, and therefore make it easier for you to help them getting neoclip to work. It might also be interesting to look into adding a `:checkhealth neoclip` command to investigate common problems, but I have no idea how to set that up.

**Comment by AckslD** [comment]
That's a great idea @DuncanvR! Would you like to add that as a PR? No problem if not :)

**Comment by DuncanvR** [comment]
I would be able to help a bit with the text, but I'm really not familiar enough with neoclip to know which steps should be included and in what order. If you don't mind continuing the discussion here, could you list what things you ask people to check?

So far I've seen (in random order):
1. `:lua print(vim.inspect(require('neoclip.storage').get()))`
1. `:autocmd TextYankPost`
1. `:set clipboard`
1. `:lua require('telescope').load_extension('neoclip')`
1. `:Telescope neoclip`
1. `:Telescope neoclip neoclip`

Any other relevant commands?

For most projects I'd suggest having different starting points depending on what goes wrong, but I think the main *"it doesn't work"* symptom here is that no yanked lines are shown in Telescope. So that makes it a little simpler (of course you can always add others later).
Since this would be a static list, we'll have to pick an order that makes sense for most configs. I reckon the first check should be whether `setup()` was actually called. That's the second item in the list above, right?
